### **Import Libraries & Functions**

In [3]:
import sys
from pathlib import Path
import pandas as pd

In [4]:
PROJECT_ROOT = Path(r"D:\Project").resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

from utils.utils import load_data, target_balance

### **Read Interim Data**

In [5]:
df = load_data("interim/interim_data.csv")
df.head(3)

,age,gender,country,company_size,industry,job_title,annual_company_revenue,plan_type,months_as_customer,total_spend,...,product_tours_completed,onboarding_completed,support_tickets_total,avg_ticket_resolution_hours,sat_score,campaigns_received,last_marketing_touch_days_ago,attended_webinar,social_media_engaged,will_repurchase
0,60,Female,USA,201 to 500,Education,Manager,75849462,Starter,32,517,...,1,1,9,5.9,5,7,100,0,1,0
1,50,Female,Canada,51 to 200,Manufacturing,CEO,16239921,Starter,25,481,...,1,0,16,26.3,4,7,171,0,0,0
2,36,Male,France,11 to 50,Healthcare,CEO,2436035,Free,52,0,...,4,1,10,2.8,3,15,66,0,0,1

### **Check Distribution**

In [10]:
target_balance(df, "will_repurchase")

                 count     pct
will_repurchase
1                 6269  0.6269
0                 3731  0.3731