### **Import Libraries & Functions**

In [1]:
import sys
import pandas as pd
from pathlib import Path
import numpy as np

In [2]:
PROJECT_ROOT = Path(r"D:\Project").resolve()
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

from utils.utils import load_data, data_checkup, check_multicollinearity

### **Read Raw Data**

In [3]:
df = load_data("raw/saas_lead.csv")
df.head(3)

,customer_id,age,gender,country,company_size,industry,job_title,annual_company_revenue,plan_type,months_as_customer,...,product_tours_completed,onboarding_completed,support_tickets_total,avg_ticket_resolution_hours,sat_score,campaigns_received,last_marketing_touch_days_ago,attended_webinar,social_media_engaged,will_repurchase
0,CUST-00001,60,Female,USA,201 to 500,Education,Manager,75849462,Starter,32,...,1,1,9,5.9,5,7,100,0,1,0
1,CUST-00002,50,Female,Canada,51 to 200,Manufacturing,CEO,16239921,Starter,25,...,1,0,16,26.3,4,7,171,0,0,0
2,CUST-00003,36,Male,France,11 to 50,Healthcare,CEO,2436035,Free,52,...,4,1,10,2.8,3,15,66,0,0,1

### **Data Eyebaling**

In [4]:
pd.set_option('display.float_format', '{:.4f}'.format)
pd.set_option('display.max_colwidth', None)

num_df, cat_df = data_checkup(df)

In [5]:
num_df

,column,num_rows,num_nulls,min,max,mean,median,std
0,age,10000,0,22.0000,64.0000,43.0020,43.0000,12.2858
1,annual_company_revenue,10000,0,50157.0000,499508097.0000,40993656.5697,6566585.0000,90222245.4232
2,months_as_customer,10000,0,1.0000,59.0000,29.9787,30.0000,17.0397
3,total_spend,10000,0,0.0000,119999.0000,12382.8689,1323.5000,25839.1369
4,num_purchases,10000,0,1.0000,19.0000,10.0292,10.0000,5.5493
5,last_purchase_days_ago,10000,0,1.0000,364.0000,184.1051,184.0000,104.6734
6,has_churned_before,10000,0,0.0000,1.0000,0.2532,0.0000,0.4349
7,discount_used,10000,0,0.0000,1.0000,0.4452,0.0000,0.4970
8,monthly_active_days,10000,0,0.0000,29.0000,14.4945,15.0000,8.6404
9,avg_session_duration_min,10000,0,0.0000,111.8000,12.0095,8.2000,12.1719
10,features_used_count,10000,0,1.0000,24.0000,12.4483,12.0000,6.9570
11,api_calls_last_30_days,10000,0,5.0000,49993.0000,25357.1413,25711.5000,14467.9607
12,product_tours_completed,10000,0,0.0000,4.0000,1.9864,2.0000,1.4158
13,onboarding_completed,10000,0,0.0000,1.0000,0.7051,1.0000,0.4560
14,support_tickets_total,10000,0,0.0000,19.0000,9.5367,10.0000,5.8036
15,avg_ticket_resolution_hours,10000,0,0.0000,141.2000,18.1120,12.5000,18.1114
16,sat_score,10000,0,1.0000,5.0000,3.7648,4.0000,1.1226
17,campaigns_received,10000,0,0.0000,29.0000,14.5451,15.0000,8.6351
18,last_marketing_touch_days_ago,10000,0,1.0000,179.0000,90.3659,90.0000,52.3889
19,attended_webinar,10000,0,0.0000,1.0000,0.3472,0.0000,0.4761
20,social_media_engaged,10000,0,0.0000,1.0000,0.4000,0.0000,0.4899
21,will_repurchase,10000,0,0.0000,1.0000,0.6269,1.0000,0.4837

In [6]:
cat_df

,column,num_rows,num_nulls,unique_options
0,customer_id,10000,0,"[CUST-00001, CUST-00002, CUST-00003, CUST-00004, CUST-00005, CUST-00006, CUST-00007, CUST-00008, CUST-00009, CUST-00010, CUST-00011, CUST-00012, CUST-00013, CUST-00014, CUST-00015, CUST-00016, CUST-00017, CUST-00018, CUST-00019, CUST-00020, CUST-00021, CUST-00022, CUST-00023, CUST-00024, CUST-00025, CUST-00026, CUST-00027, CUST-00028, CUST-00029, CUST-00030, CUST-00031, CUST-00032, CUST-00033, CUST-00034, CUST-00035, CUST-00036, CUST-00037, CUST-00038, CUST-00039, CUST-00040, CUST-00041, CUST-00042, CUST-00043, CUST-00044, CUST-00045, CUST-00046, CUST-00047, CUST-00048, CUST-00049, CUST-00050, CUST-00051, CUST-00052, CUST-00053, CUST-00054, CUST-00055, CUST-00056, CUST-00057, CUST-00058, CUST-00059, CUST-00060, CUST-00061, CUST-00062, CUST-00063, CUST-00064, CUST-00065, CUST-00066, CUST-00067, CUST-00068, CUST-00069, CUST-00070, CUST-00071, CUST-00072, CUST-00073, CUST-00074, CUST-00075, CUST-00076, CUST-00077, CUST-00078, CUST-00079, CUST-00080, CUST-00081, CUST-00082, CUST-00083, CUST-00084, CUST-00085, CUST-00086, CUST-00087, CUST-00088, CUST-00089, CUST-00090, CUST-00091, CUST-00092, CUST-00093, CUST-00094, CUST-00095, CUST-00096, CUST-00097, CUST-00098, CUST-00099, CUST-00100, ...]"
1,gender,10000,0,"[Female, Male, Other]"
2,country,10000,0,"[USA, Canada, France, Australia, Germany, UK, Brazil, India]"
3,company_size,10000,0,"[201 to 500, 51 to 200, 11 to 50, 1 to 10, Above 500]"
4,industry,10000,0,"[Education, Manufacturing, Healthcare, Retail, Tech, Media, Finance]"
5,job_title,10000,0,"[Manager, CEO, Analyst, VP Sales, Developer, CTO, Marketing Lead]"
6,plan_type,10000,0,"[Starter, Free, Pro, Enterprise]"

### **Check Multicolinarity**

In [7]:
vif_df = check_multicollinearity(df, threshold=5.0)
display(vif_df)

                          feature     VIF  high_vif
0                             age 10.7417      True
1                       sat_score 10.5377      True
2             monthly_active_days  4.6530     False
3             features_used_count  4.0807     False
4                   num_purchases  4.0674     False
5          last_purchase_days_ago  4.0490     False
6              months_as_customer  3.9187     False
7          api_calls_last_30_days  3.8741     False
8   last_marketing_touch_days_ago  3.8012     False
9                 will_repurchase  3.7957     False
10             campaigns_received  3.6511     False
11          support_tickets_total  3.5211     False
12           onboarding_completed  3.3134     False
13        product_tours_completed  2.8769     False
14    avg_ticket_resolution_hours  1.9566     False
15       avg_session_duration_min  1.9496     False
16                  discount_used  1.7804     False
17           social_media_engaged  1.6451     False
18               attended_webinar  1.5245     False
19             has_churned_before  1.3363     False
20                    total_spend  1.2273     False
21         annual_company_revenue  1.2038     False

In [8]:
# Check corr between age and satisfaction_score
df[['age', 'sat_score']].corr()

             age  sat_score
age       1.0000     0.0110
sat_score 0.0110     1.0000

In [9]:
# Check corr between age and other numeric features
num_df = df.select_dtypes(include=['number']).drop(columns=['will_repurchase'])
num_df.corr()['age'].sort_values(ascending=False)

age                              1.0000
months_as_customer               0.0224
total_spend                      0.0135
has_churned_before               0.0123
sat_score                        0.0110
annual_company_revenue           0.0108
campaigns_received               0.0090
support_tickets_total            0.0078
num_purchases                    0.0066
monthly_active_days              0.0056
avg_session_duration_min         0.0026
last_purchase_days_ago           0.0026
product_tours_completed          0.0017
last_marketing_touch_days_ago   -0.0018
avg_ticket_resolution_hours     -0.0026
api_calls_last_30_days          -0.0028
attended_webinar                -0.0037
features_used_count             -0.0042
social_media_engaged            -0.0148
discount_used                   -0.0173
onboarding_completed            -0.0179
Name: age, dtype: float64

In [10]:
# Check corr between satisfaction_score and other numeric features
num_df = df.select_dtypes(include=['number']).drop(columns=['will_repurchase'])
num_df.corr()['sat_score'].sort_values(ascending=False)

sat_score                        1.0000
num_purchases                    0.0119
last_marketing_touch_days_ago    0.0113
age                              0.0110
discount_used                    0.0092
social_media_engaged             0.0038
features_used_count              0.0037
avg_session_duration_min         0.0036
last_purchase_days_ago           0.0031
onboarding_completed             0.0022
product_tours_completed          0.0009
total_spend                      0.0009
api_calls_last_30_days           0.0006
months_as_customer              -0.0015
campaigns_received              -0.0023
annual_company_revenue          -0.0026
has_churned_before              -0.0038
monthly_active_days             -0.0064
attended_webinar                -0.0104
support_tickets_total           -0.0252
avg_ticket_resolution_hours     -0.0277
Name: sat_score, dtype: float64